### ISSUE TITLE
Error: "Exiting meeting because room was deleted"

### ISSUE THREAD

**Issue by mayurbagade456** [adrianhajdin/ai_mock_interviews#7]
![Image](https://github.com/user-attachments/assets/78595d29-caab-40b5-bc59-37231b7a7acb)

does anybody know how this can be fixed (Hint: The same error shown at the Vapi Dashboard)

**Comment by P47Parzival** [comment]
I am getting the same error, did you find the result if yes pls help me with that sir!

**Comment by P47Parzival** [comment]
Well i came across this issue too let me give you my code mine issue is solved
interview.action.ts
"use server";

import { db } from "@/firebase/admin";

interface CreateInterviewParams {
  userId: string;
  role: string;
  type: string;
  techstack: string[];
  finalized: boolean;
}

export async function createInterview(params: CreateInterviewParams) {
  const { userId, role, type, techstack, finalized } = params;

  try {
    const interviewRef = db.collection("interviews").doc();
    
    const interview = {
      userId,
      role,
      type,
      techstack,
      finalized,
      createdAt: new Date().toISOString(),
    };

    await interviewRef.set(interview);

    return { success: true, interviewId: interviewRef.id };
  } catch (error) {
    console.error("Error creating interview:", error);
    return { success: false };
  }
} 

page.tsx for interview section 
import Agent from "@/components/Agent";
import { getCurrentUser } from "@/lib/actions/auth.action";

const Page = async () => {
  const user = await getCurrentUser();

  return (
    <>
      <h3>Interview generation</h3>

      <Agent
        userName={user?.name!}
        userId={user?.id}
        profileImage={user?.profileURL}
        type="generate"
      />
    </>
  );
};

export default Page;

**Comment by Sebrey-young** [comment]
> Well i came across this issue too let me give you my code mine issue is solved interview.action.ts "use server";
> 
> import { db } from "@/firebase/admin";
> 
> interface CreateInterviewParams { userId: string; role: string; type: string; techstack: string[]; finalized: boolean; }
> 
> export async function createInterview(params: CreateInterviewParams) { const { userId, role, type, techstack, finalized } = params;
> 
> try { const interviewRef = db.collection("interviews").doc();
> 
> ```
> const interview = {
>   userId,
>   role,
>   type,
>   techstack,
>   finalized,
>   createdAt: new Date().toISOString(),
> };
> 
> await interviewRef.set(interview);
> 
> return { success: true, interviewId: interviewRef.id };
> ```
> 
> } catch (error) { console.error("Error creating interview:", error); return { success: false }; } }
> 
> page.tsx for interview section import Agent from "@/components/Agent"; import { getCurrentUser } from "@/lib/actions/auth.action";
> 
> const Page = async () => { const user = await getCurrentUser();
> 
> return ( <>
> 
> ### Interview generation
> ```
>   <Agent
>     userName={user?.name!}
>     userId={user?.id}
>     profileImage={user?.profileURL}
>     type="generate"
>   />
> </>
> ```
> 
> ); };
> 
> export default Page;

I am having the same Error and this does not fix it for me sadly.
